# Generated by Django 3.2.16 on 2023-02-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoParcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.IntegerField()),
                ('dt_vencimento', models.DateField()),
                ('vl_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_credito', models.DateField()),
            ],
            options={
                'verbose_name': 'ContratoParcela',
                'verbose_name_plural': 'ContratoParcelas',
            },
        ),
    ]
