# Generated by Django 3.2.16 on 2023-02-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratoparcela',
            options={'managed': False, 'verbose_name': 'ContratoParcela', 'verbose_name_plural': 'ContratoParcelas'},
        ),
    ]
