# Generated by Django 3.2.16 on 2023-02-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contratos', verbose_name='')),
                ('parcelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contratoparcelas', verbose_name='')),
            ],
            options={
                'verbose_name': 'ConsolidadoVendedor',
                'verbose_name_plural': 'ConsolidadoVendedors',
            },
        ),
        migrations.DeleteModel(
            name='ContratoParcela',
        ),
    ]
