# Generated by Django 3.2.16 on 2023-02-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo_repasse',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
