# Generated by Django 3.2.16 on 2023-03-11 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vendedor', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('id_contrato', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('comprador', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('nu_parcela', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('contrato', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('dt_vencimento', models.DateField(blank=True, null=True, verbose_name='')),
                ('dt_credito', models.DateField(blank=True, null=True, verbose_name='')),
                ('banco', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('evento', models.CharField(blank=True, max_length=512, null=True, verbose_name='')),
                ('deposito', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('adi', models.CharField(blank=True, max_length=12, null=True, verbose_name='')),
                ('me', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('op', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('repasses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('comissao', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Dado',
                'verbose_name_plural': 'Dados',
                'db_table': 'dado',
            },
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('tipo', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('dt_taxa', models.DateField(blank=True, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'taxas',
                'verbose_name_plural': 'taxas',
                'db_table': 'taxas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RepasseRetido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_rep_retido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('dt_rep_retido', models.DateField(blank=True, null=True, verbose_name='')),
                ('tipo', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'RepasseRetido',
                'verbose_name_plural': 'RepasseRetidos',
                'db_table': 'repasse_retido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_debito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('dt_debitado', models.DateField(blank=True, null=True, verbose_name='')),
                ('descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'debito',
                'verbose_name_plural': 'debitos',
                'db_table': 'debito',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_creditado', models.DateField(blank=True, null=True, verbose_name='')),
                ('vl_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'credito',
                'verbose_name_plural': 'creditos',
                'db_table': 'credito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calculo_Repasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('adi', models.CharField(blank=True, max_length=12, null=True, verbose_name='')),
                ('me', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('op', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('banco', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('repasses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('nu_parcela', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('comissao', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('dt_credito', models.DateField(blank=True, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('contrato_parcelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.contratoparcelas')),
                ('id_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.contratos')),
                ('id_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'calculo_repasse',
                'verbose_name_plural': 'calculo_repasses',
                'db_table': 'Calculo_Repasse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxas')),
                ('sim', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('nao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('operacional', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('tcc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('animal', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('evento', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('informar_repasse', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('vl_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vl_boletos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'cad_cliente',
                'verbose_name_plural': 'cad_clientes',
                'db_table': 'cad_cliente',
                'managed': True,
            },
        ),
    ]
