# Generated by Django 3.2.16 on 2023-03-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cadcliente_calculo_repasse_credito_dado_debito_repasseretido_taxa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False, 'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
