# Generated by Django 3.2.16 on 2023-02-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contratoparcela_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contratoparcela',
            table='contrato_parcelas',
        ),
    ]
