# Generated by Django 3.2.16 on 2023-02-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230208_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAD_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxas')),
                ('vendedor', models.CharField(max_length=128, verbose_name='')),
                ('codigo', models.IntegerField(verbose_name='')),
                ('sim', models.IntegerField(default=0.03, verbose_name='')),
                ('nao', models.IntegerField(default=0.2, verbose_name='')),
                ('operacional', models.IntegerField(default=0.05, verbose_name='')),
                ('tcc', models.DecimalField(decimal_places=2, default=0.01, max_digits=5, verbose_name='')),
                ('honorarios', models.DecimalField(decimal_places=2, default=0.03, max_digits=5, verbose_name='')),
                ('animal', models.CharField(max_length=50, verbose_name='')),
                ('evento', models.CharField(max_length=128, verbose_name='')),
                ('informar_repasse', models.CharField(max_length=50, verbose_name='')),
                ('vl_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('vl_boletos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('vl_pago', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('repasse', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
            ],
            options={
                'verbose_name': 'CAD_Cliente',
                'verbose_name_plural': 'CAD_Clientes',
            },
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(max_length=50, verbose_name='')),
                ('calculo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('taxas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('adi', models.BooleanField(verbose_name='')),
                ('me', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('op', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
            ],
            options={
                'verbose_name': 'repasse',
                'verbose_name_plural': 'repasses',
            },
        ),
        migrations.AlterField(
            model_name='consolidadovendedor',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.contratos'),
        ),
        migrations.RemoveField(
            model_name='consolidadovendedor',
            name='parcelas',
        ),
        migrations.AddField(
            model_name='consolidadovendedor',
            name='parcelas',
            field=models.ManyToManyField(to='home.ContratoParcelas'),
        ),
        migrations.CreateModel(
            name='CAD_Cliente_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxas')),
                ('sim', models.IntegerField(blank=True, default=0.03, null=True, verbose_name='')),
                ('nao', models.IntegerField(blank=True, default=0.2, null=True, verbose_name='')),
                ('operacional', models.IntegerField(blank=True, default=0.05, null=True, verbose_name='')),
                ('tcc', models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=5, null=True, verbose_name='')),
                ('honorarios', models.DecimalField(blank=True, decimal_places=2, default=0.03, max_digits=5, null=True, verbose_name='')),
                ('animal', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('evento', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('informar_repasse', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('vl_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vl_boletos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'cad_cliente_model',
                'verbose_name_plural': 'cad_cliente_models',
            },
        ),
    ]
