# Generated by Django 3.2.16 on 2023-02-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_calculo_repasse_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo_repasse',
            name='repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
    ]
