# Generated by Django 3.2.16 on 2023-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230211_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_cliente_model',
            name='animal',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
    ]
