# Generated by Django 3.2.16 on 2023-03-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_calculo_repasse_repasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cadcliente')),
            ],
            options={
                'verbose_name': 'taxas',
                'verbose_name_plural': 'taxas',
                'db_table': 'taxas',
                'managed': True,
            },
        ),
    ]
