# Generated by Django 3.2.16 on 2023-03-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230313_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcliente',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pessoas'),
        ),
    ]
