# Generated by Django 3.2.16 on 2023-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cadcliente_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='contrato',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
    ]
