# Generated by Django 3.2.16 on 2023-02-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cad_cliente_model_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cad_cliente_model',
            options={'managed': True, 'verbose_name': 'cad_cliente_model', 'verbose_name_plural': 'cad_cliente_models'},
        ),
    ]
