# Generated by Django 3.2.16 on 2023-03-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230301_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
    ]
