# Generated by Django 3.2.16 on 2023-03-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_taxa_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'managed': True, 'verbose_name': 'credito', 'verbose_name_plural': 'creditos'},
        ),
        migrations.AddField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
        migrations.AddField(
            model_name='credito',
            name='dt_creditado',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='credito',
            name='taxas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.taxa'),
        ),
        migrations.AddField(
            model_name='credito',
            name='vl_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterModelTable(
            name='credito',
            table='credito',
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_debito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('dt_debito', models.DateField(auto_now_add=True, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.cadcliente')),
                ('taxas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.taxa')),
            ],
            options={
                'verbose_name': 'debito',
                'verbose_name_plural': 'debitos',
            },
        ),
    ]
