# Generated by Django 3.2.16 on 2023-03-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230301_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='debito',
            name='descricao',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
    ]
