# Generated by Django 3.2.16 on 2023-02-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230212_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_cliente_model',
            name='nao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cad_cliente_model',
            name='operacional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cad_cliente_model',
            name='sim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
    ]
