# Generated by Django 3.2.16 on 2023-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_dado_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='parcelas_contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='dado',
            name='contrato',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
    ]
