# Generated by Django 3.2.16 on 2023-02-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230212_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo_Repasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('adi', models.CharField(blank=True, max_length=12, null=True, verbose_name='')),
                ('me', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('op', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('repasses', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('vl_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='')),
                ('id_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contratos')),
                ('id_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'calculo_repasse',
                'verbose_name_plural': 'calculo_repasses',
                'db_table': 'Calculo_Repasse',
            },
        ),
    ]
