# Generated by Django 3.2.16 on 2023-03-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_credito_descricao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='debito',
            table='debito',
        ),
    ]
