# Generated by Django 3.2.16 on 2023-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_calculo_repasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo_repasse',
            name='calculo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='deposito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='me',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='op',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='repasses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='taxas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='vl_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
    ]
