# Generated by Django 3.2.16 on 2023-03-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_debito_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
    ]
