# Generated by Django 3.2.16 on 2023-02-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230213_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo_repasse',
            name='deposito',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
    ]
