# Generated by Django 3.2.16 on 2023-02-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_calculo_repasse_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao_Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'Comissao_Vendedor',
                'verbose_name_plural': 'Comissao_Vendedores',
                'db_table': 'comissao_vendedor',
                'managed': True,
            },
        ),
    ]
