# Generated by Django 3.2.16 on 2023-03-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_debito_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debito',
            old_name='dt_debito',
            new_name='dt_debitado',
        ),
    ]
