# Generated by Django 3.2.16 on 2023-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_dt_debito_debito_dt_debitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='dt_creditado',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='debito',
            name='dt_debitado',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
