# Generated by Django 3.2.16 on 2023-02-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comissao_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao_vendedor',
            name='percentual',
        ),
        migrations.AddField(
            model_name='comissao_vendedor',
            name='codigo_parcela',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='comissao_vendedor',
            name='id_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contratos'),
        ),
        migrations.AddField(
            model_name='comissao_vendedor',
            name='nome',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='comissao_vendedor',
            name='numero_contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='comissao_vendedor',
            name='taxa_de_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='comissao_vendedor',
            name='taxa_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
    ]
