# Generated by Django 3.2.16 on 2023-02-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230214_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidadovendedor',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='consolidadovendedor',
            name='parcelas',
        ),
        migrations.DeleteModel(
            name='Repasse',
        ),
        migrations.DeleteModel(
            name='ConsolidadoVendedor',
        ),
    ]
