# Generated by Django 3.2.16 on 2023-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230302_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='dt_taxa',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
