# Generated by Django 3.2.16 on 2023-03-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_taxa_dt_taxa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxa',
            name='cliente',
        ),
    ]
