# Generated by Django 3.2.16 on 2023-03-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_dado_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='contrato',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='dado',
            name='evento',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
