# Generated by Django 3.2.16 on 2023-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230214_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo_repasse',
            name='comissao',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='calculo_repasse',
            name='nu_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
