# Generated by Django 3.2.16 on 2023-03-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_taxa_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
    ]
