# Generated by Django 3.2.16 on 2023-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230318_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadcliente',
            name='repasse_semanal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
    ]
