# Generated by Django 3.2.16 on 2023-02-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230214_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculo_repasse',
            old_name='nu_parcelas',
            new_name='nu_parcela',
        ),
    ]
