# Generated by Django 3.2.16 on 2023-03-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_taxa_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='taxas',
        ),
        migrations.RemoveField(
            model_name='debito',
            name='taxas',
        ),
    ]
