# Generated by Django 3.2.16 on 2023-03-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20230302_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasseRetido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_rep_retido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='')),
                ('dt_rep_retido', models.DateField(blank=True, null=True, verbose_name='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'RepasseRetido',
                'verbose_name_plural': 'RepasseRetidos',
                'db_table': 'repasse_retido',
                'managed': True,
            },
        ),
    ]
