# Generated by Django 3.2.16 on 2023-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_repasseretido'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasseretido',
            name='tipo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
    ]
