# Generated by Django 3.2.16 on 2023-02-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_calculo_repasse_repasse_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo_repasse',
            name='repasse_calc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=''),
        ),
    ]
