# Generated by Django 3.2.16 on 2023-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_repasseretido_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comissao_Vendedor',
        ),
    ]
