# Generated by Django 3.2.16 on 2023-02-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20230216_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='evento',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
    ]
