# Generated by Django 3.2.16 on 2023-02-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_dado_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='evento',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=''),
        ),
    ]
