# Generated by Django 3.2.16 on 2023-02-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_dado_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='nu_parcela',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
