# Generated by Django 3.2.16 on 2023-02-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_dado_nu_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='dado',
            name='nu_parcela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
