# Generated by Django 3.2.16 on 2023-02-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20230216_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo_repasse',
            name='dt_credito',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
