# Generated by Django 3.2.16 on 2023-02-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_calculo_repasse_dt_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quinzenal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Quinzenal',
                'verbose_name_plural': 'Quinzenais',
                'db_table': 'quinzenal',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='cad_cliente_model',
            options={'managed': True, 'verbose_name': 'cad_cliente', 'verbose_name_plural': 'cad_clientes'},
        ),
        migrations.AddField(
            model_name='calculo_repasse',
            name='contrato_parcelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.contratoparcelas'),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='id_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.contratos'),
        ),
        migrations.AlterField(
            model_name='calculo_repasse',
            name='id_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
        migrations.AlterModelTable(
            name='cad_cliente_model',
            table='cad_cliente',
        ),
    ]
